#!/bin/sh
GTKDIALOG=gtkdialog
export about_dialog='

<window title="About Systeminfo" icon-name="dialog-information-symbolic" resizable="false" width-request="500" height-request="auto">
  <vbox>
    <pixmap>
      <input file icon="dialog-information-symbolic"></input>
      <height>70</height><width>70</width>
    </pixmap>
  <hseparator width-request="auto"></hseparator>
    <text use-markup="true"><label>"<b>xfce4-sysinfo</b>"</label></text>
    <text justify="2"><label>A little application to show systeminfos in xfce and expand the xfce settings</label></text>
    <text><label>Created by: lxgr [lxgr@protonmail.com]</label></text>
    <hbox homogeneous="true">
      <hbox>
        <text><label>Homepage: </label></text>
        <text selectable="true" use-markup="false">
          <label>https://github.com/lxgr-linux/xfce4-sysinfo</label>
        </text>
      </hbox>
    </hbox>
    <text><label>Version: '$(pacman -Qs xfce4-sysinfo | egrep xfce4-sysinfo | awk {'print $2'})'</label></text>
    <hseparator width-request="auto"></hseparator>
    <hbox>
      <button>
        <input file icon="software-update-available-symbolic"></input>
        <label>"Update this software"</label>
        <action>zenity --info --text "The latest version of this software will be downloaded and installed from the AUR. You will have to type in your password!" && xfce4-terminal -x sh -c "mkdir ~/.build_AUR ; cd ~/.build_AUR ; echo :: Cloning git repository ; git clone https://aur.archlinux.org/xfce4-sysinfo.git ; cd ./xfce4-sysinfo ; echo :: Making and installing the package ; makepkg -sif ; cd ; echo :: Cleaning up ; sudo rm -r ~/.build_AUR ; echo :: Done! ; zenity --info --text "Done!""</action>
      </button>
      <button>
        <input file icon="application-exit"></input>
        <label>"Exit"</label>
      </button>
    </hbox>
  </vbox>
</window>
'


export MAIN_DIALOG='

<window title="Systeminfo" icon-name="preferences-desktop" resizable="true" width-request="auto" height-request="auto">
 <vbox>
  <frame Systeminfo>
    <hbox homogeneous="true">
      <vbox>
        <text height-request="0"><label>" "</label></text>
        <text use-markup="true"><label>"<b>General: </b>"</label></text>
        <text><label> Operatingsystem: '$(egrep PRETTY_NAME /etc/os-release | sed -e 's/"/ /g' | awk {'print $2, $3,$4, $5'})'</label></text>
        <text><label> Kernel: '$(uname -msr)'</label></text>
        <text><label> XFCE version: '$(xfce4-session -V | egrep xfce4-session | awk {'print $2'})'</label></text>
        <hbox homogeneous="true">
          <hbox>
            <text><label>Installed Packages: '$( pacman -Qq | wc -l)' (pacman)</label></text>
            <button>
              <input file icon="software-update-available-symbolic"></input>
              <label>"Install updates"</label>
              <action>zenity --password --title "Password" | sudo -S xfce4-terminal -x pacman -Syu ; zenity --info --text "Done!"</action>
            </button>
          </hbox>
        </hbox>
        <hbox homogeneous="true">
          <hbox>
            <text><label> Hostname: '$(hostname)'</label></text>
            <button>
              <input file icon="document-edit"></input>
              <label>"Change hostname"</label>
              <action>zenity --password --title "Password"| sudo -S hostnamectl set-hostname $(zenity --entry --text "Set new hostname:" --entry-text $(hostname) --title="New Hostname")</action>
            </button>
          </hbox>
        </hbox>
        <vbox>
          <text><label>" "</label></text>
          <text use-markup="true"><label>"<b>Hardware: </b>"</label></text>
          <text><label> CPU: '$(lscpu | egrep Modellname | awk {'print $2,$3,$4,$5,$6,$7,$8,$9,$10'})'</label></text>
          <text><label> GPU: '$(lspci | egrep VGA | awk {'print $5,$6,$7,$8,$9,$10,$11'})'</label></text>
          <text><label> RAM: '$(free -h | egrep Speicher | awk {'print $2'})'</label></text>
          <text><label> Disk used: '$(df -h | egrep -w ' /' | awk {'print $3'})'/'$(df -h | egrep -w ' /' | awk {'print $2'})'</label></text>
        </vbox>
      </vbox>
      <vbox homogeneous="true">
        <pixmap>
          <input file>/usr/share/xfce4-sysinfo/icons/'$(egrep LOGO /etc/os-release | sed -e 's/=/ /g' | awk {'print $2'})'.svg</input>
          <height>120</height><width>120</width>
        </pixmap>
      </vbox>
    </hbox>
  </frame>
  <hseparator width-request="auto"></hseparator>
  <hbox>
    <button>
      <input file icon="dialog-information-symbolic"></input>
      <label>"About"</label>
      <action>gtkdialog --program=about_dialog & </action>
    </button>
    <button>
      <input file icon="application-exit"></input>
      <label>"Exit"</label>
    </button>
  </hbox>
 </vbox>
</window>
'

gtkdialog --program=MAIN_DIALOG
