#!/bin/bash

. /etc/os-release

update(){
  echo "The latest version of this software will be downloaded and installed from the AUR. You will have to type in your password! Do you want this? (y/n)"
  read ans
  if [ $ans == y ]
    then
      mkdir ~/.build_AUR
      cd ~/.build_AUR
      echo :: Cloning git repository
      git clone https://aur.archlinux.org/xfce4-sysinfo.git
      cd ./xfce4-sysinfo
      echo :: Making and installing the package
      makepkg -sif
      cd
      echo :: Cleaning up
      sudo rm -r ~/.build_AUR
      echo :: Done!
  fi
  echo :: Exit
}

general(){

export about_dialog='

<window title="About Systeminfo" icon-name="dialog-information-symbolic" resizable="true" width-request="500" height-request="auto">
  <vbox>
    <pixmap>
      <input file icon="dialog-information-symbolic"></input>
      <height>70</height><width>70</width>
    </pixmap>
  <hseparator width-request="auto"></hseparator>
    <text use-markup="true"><label>"<b>xfce4-sysinfo</b>"</label></text>
    <text justify="2"><label>A little application to show systeminfos in xfce and expand the xfce settings</label></text>
    <text><label>Created by: lxgr [lxgr@protonmail.com]</label></text>
    <hbox homogeneous="true">
      <hbox>
        <text><label>Homepage: </label></text>
        <button relief="2">
          <action>exo-open --launch WebBrowser https://github.com/lxgr-linux/xfce4-sysinfo</action>
          <label>https://github.com/lxgr-linux/xfce4-sysinfo</label>
        </button>
      </hbox>
    </hbox>
    <text><label>Version: '$(pacman -Qs xfce4-sysinfo  | egrep xfce4-sysinfo | awk {'print $2'} ; tail -n1 /usr/share/xfce4-sysinfo/version)'</label></text>
    <text><label>" "</label></text>
    <hseparator width-request="auto"></hseparator>
    <hbox spacing="0">
      <button width-request="100">
        <input file icon="dialog-information-symbolic"></input>
        <height>18</height>
        <label>"License"</label>
        <action>exo-open --launch TerminalEmulator sh -c "cat /usr/share/licenses/xfce4-sysinfo/LICENSE | less"</action>
      </button>
      <button>
        <input file icon="software-update-available-symbolic"></input>
        <height>18</height>
        <label>"Update this software"</label>
        <action>zenity --info --text "The latest version of this software will be downloaded and installed from the AUR. You will have to type in your password!" && exo-open --launch TerminalEmulator sh -c "mkdir ~/.build_AUR ; cd ~/.build_AUR ; echo :: Cloning git repository ; git clone https://aur.archlinux.org/xfce4-sysinfo.git ; cd ./xfce4-sysinfo ; echo :: Making and installing the package ; makepkg -sif ; cd ; echo :: Cleaning up ; sudo rm -r ~/.build_AUR ; echo :: Done! ; zenity --info --text "Done!""</action>
      </button>
      <button use-stock="true" label="gtk-quit" width-request="100">
      </button>
    </hbox>
  </vbox>
</window>
'


export MAIN_DIALOG='

<window title="Systeminfo" icon-name="preferences-desktop" resizable="false" width-request="700" height-request="auto">
 <vbox>
  <hbox space-expand="true">
    <hbox xalign="0">
      <hbox width-request="auto">
       <pixmap xalign="0">
         <input file icon="dialog-information-symbolic"></input>
         <height>60</height><width>60</width>
       </pixmap>
      </hbox>
       <vbox homogeneous="true" width-request="620" space-fill="true">
         <text use-markup="true"  justify="0" wrap="true" xalign="0"><label>"<b><big>Systeminfo</big></b>
Here you can see your systems information"</label></text>
      </vbox>
      </hbox>
    </hbox>
   <frame>
     <notebook show-tabs="false">
       <hbox homogeneous="true">
         <vbox>
           <text height-request="0"><label>" "</label></text>
           <text use-markup="true"><label>"<b>General: </b>"</label></text>
           <text wrap="true" width-chars="46"><label> Operatingsystem: '$PRETTY_NAME'</label></text>
           <text wrap="true" width-chars="46"><label> Kernel: '$(uname -msr)'</label></text>
           <text wrap="true" width-chars="46"><label> XFCE version: '$(xfce4-session -V | egrep xfce4-session | awk {'print $2'})'</label></text>
           <hbox homogeneous="true" spacing="0">
             <hbox spacing="0">
               <text wrap="true"><label>Installed Packages: '$(sh -c "pacman -Qq || apt list --installed" | wc -l)'</label></text>
               <button relief="2">
                 <input file icon="software-update-available-symbolic"></input>
                 <height>18</height>
                 <label>"Update"</label>
                 <action>zenity --info --text "Your system will be updated" && zenity --password --title "Password" | sudo -S exo-open --launch TerminalEmulator sh -c "pacman -Syu || apt update && apt-get dist-upgrade; echo :: Done; zenity --info --text "Done!""</action>
               </button>
             </hbox>
           </hbox>
        <hbox homogeneous="true" spacing="0">
          <hbox spacing="0">
            <text wrap="true" auto-refresh="true"><label> Hostname: '$(hostname)'</label></text>
            <button relief="2">
              <input file icon="document-edit"></input>
              <height>18</height>
              <label>"Change hostname"</label>
              <action>zenity --password --title "Password"| sudo -S hostnamectl set-hostname $(zenity --entry --text "Set new hostname:" --entry-text $(hostname) --title="New Hostname")</action>
            </button>
          </hbox>
        </hbox>
        <vbox>
          <text><label>" "</label></text>
          <text use-markup="true"><label>"<b>Hardware: </b>"</label></text>
          <text wrap="true" width-chars="46"><label> CPU: '$(egrep "model name" /proc/cpuinfo | uniq | awk {'print $4,$5,$6,$7,$8,$9,$10,$11,$12'})'</label></text>
          <text wrap="true" width-chars="46"><label> GPU: '$(lspci | egrep VGA | awk {'print $5,$6,$7,$8,$9,$10,$11'})' '$(lspci | egrep 3D | awk {'print $4,$5,$6,$7,$8,$9,$10,$11'})'</label></text>
          <text wrap="true" width-chars="46"><label> RAM: '$(free -h | sed -n '2p' | awk {'print $2'})'</label></text>
          <text wrap="true" width-chars="46"><label> Disk used: '$(df -h | egrep -w ' /' | awk {'print $3'})'/'$(df -h | egrep -w ' /' | awk {'print $2'})'</label></text>
          <text><label>" "</label></text>
        </vbox>
      </vbox>
      <vbox homogeneous="true">
        <pixmap auto-refresh="true">
          <input file>/usr/share/xfce4-sysinfo/icons/'$ID'.svg</input>
          <height>150</height><width>150</width>
        </pixmap>
      </vbox>
    </hbox>
  </notebook>
  </frame>
  <hbox spacing="0">
    <button use-stock="true" label="gtk-about" width-request="100">
      <action>gtkdialog --program=about_dialog & </action>
    </button>
    <button use-stock="true" label="gtk-quit" width-request="100">
    </button>
  </hbox>
 </vbox>
</window>
'
}
case $1 in
    -s|--start)
    general
    gtkdialog --program=MAIN_DIALOG
    exit 0
    ;;
		-h|--help)
                echo "xfce4-sysinfo"
                echo "Usage: $0 <option> <string>"
                echo "      -s|--start   : Starts xfce4-sysinfo"
                echo "      -a|--about   : Displays about-dialog"
                echo "      -v|--version : Displays version"
                echo "      -c|--console : Just gives console output"
                echo "      -d|--distro  : Specifys the logo which is printed out (possible options: $(ls /usr/share/xfce4-sysinfo/icons/ | sed s/.svg/""/g | xargs))"
                echo "      -l|--license : Displays license"
                echo "      -u|--upgrade : Updates this software via the AUR (will just work on archlinux!)"
                echo "      -h|--help    : Displays this help-dialog"
                echo "      --help-logo  : Displays help for your distributions logo in the systeminfo dialog"
		exit 0
		;;
    -u|--update)
      update
    exit 0
    ;;
    -c|--console)
      echo General:
      echo "  Operatingsystem:" $PRETTY_NAME
      echo "  Kernel:" $(uname -msr)
      echo "  XFCE version:" $(xfce4-session -V | egrep xfce4-session | awk {'print $2'})
      echo "  Installed Packages:" $(sh -c "pacman -Qq || apt list --installed" | wc -l)
      echo "  Hostname: $(hostname)"
      echo Hardware:
      echo "  CPU:" $(egrep "model name" /proc/cpuinfo | uniq | awk {'print $4,$5,$6,$7,$8,$9,$10,$11,$12'})
      echo "  GPU:" $(lspci | egrep VGA | awk {'print $5,$6,$7,$8,$9,$10,$11'}) $(lspci | egrep 3D | awk {'print $4,$5,$6,$7,$8,$9,$10,$11'})
      echo "  RAM:" $(free -h | sed -n '2p' | awk {'print $2'})
      echo "  Disk used:" $(df -h | egrep -w ' /' | awk {'print $3'})'/'$(df -h | egrep -w ' /' | awk {'print $2'})
    exit 0
    ;;
    -d|--distro)
      ID=$2
      echo :: $ID
      general
      gtkdialog --program=MAIN_DIALOG
    exit 0
    ;;
    -l|--license)
      cat /usr/share/licenses/xfce4-sysinfo/LICENSE | less
    exit 0
    ;;
    -a|--about)
      general
      gtkdialog --program=about_dialog
    exit 0
    ;;
    --help-logo)
      echo "This is the help/info text for your distributions logo in the systeminfo dialog:"
      echo "     The available logos are stored in /usr/share/xfce4-sysinfo/icons."
      echo "     If the logo of the Distribution you are using is not displayed, you can copy it to /usr/share/xfce4-sysinfo/icons"
      echo "     Name it $ID.svg"
    exit 0
    ;;
    -v|--version)
      echo $(pacman -Qs xfce4-sysinfo | egrep xfce4-sysinfo | awk {'print $2'} ; tail -n1 /usr/share/xfce4-sysinfo/version))
    exit 0
    ;;
    * )
      general
      gtkdialog --program=MAIN_DIALOG
    exit 0
    ;;
esac
